name: Deploy to RackNerd

on:
  push:
    branches:
      - vps-migrate-2  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }} # Usually 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/my-flask-app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask_app